#!/bin/sh

set -e

# $1 var value
# $2 var name
exitWhenVarIsEmpty () {
  if [ -z "$1" ]; then
    echo "error: ${2} is not defined"
    exit 1
  fi
}

if [ "$1" == '/usr/sbin/sockd' ]; then
  # check vars
  exitWhenVarIsEmpty "$INTERNAL" INTERNAL
  exitWhenVarIsEmpty "$PORT" PORT
  exitWhenVarIsEmpty "$EXTERNAL" EXTERNAL

  # update config
  sed -i'' -e "s/INTERNAL/$INTERNAL/" /etc/sockd.conf
  sed -i'' -e "s/PORT/$PORT/" /etc/sockd.conf
  sed -i'' -e "s/EXTERNAL/$EXTERNAL/" /etc/sockd.conf
fi

exec "$@"
